version: '3'
services:
  mysql_db:
    image: mysql
    container_name: mysql_db
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=printerest
    volumes:
      - mysql_db: /var/lib/mysql
    networks:
      - node-network

volumes: 
  mysql_db: 
    driver: local
networks:
  node-network:
    